# syntax=docker/dockerfile:1

FROM node:20-alpine AS builder

WORKDIR /app

# Установим pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Копируем только необходимые файлы для установки зависимостей
COPY ../../pnpm-workspace.yaml ../../package.json ./
COPY ./package.json ./
COPY ./prisma ./prisma

# Устанавливаем зависимости и билдим проект
RUN pnpm install --frozen-lockfile --filter ./ && \
    pnpm exec prisma generate && \
    pnpm run build

# Production image
FROM node:20-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY ./package.json ./

ENV NODE_ENV=production

CMD ["node", "dist/main"]
