name: Deploy release on alwaysdata environment
on:
    push:
        tags:
            - "v*" # Запускается при пуше тегов, начинающихся с 'v'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy NodeJS app
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.SSH_HOST}}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd app
                      git checkout main
                      git pull
                      ./migrator.sh
                      pnpm i
                      npx lerna run build -- scope backend
                      pm2 restart all
