name: Deploy release on alwaysdata environment
on:
    push:
        tags:
            - "v*" # Запускается при пуше тегов, начинающихся с 'v'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy NodeJS app
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.SSH_HOST}}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd $HOME/abai-multi-tenent
                      git checkout main
                      git pull
                      pnpm i
                      npx lerna run build
                      curl --basic --user "${{ secrets.ALWAYSDATA_TOKEN }} account=${{ secrets.ALWAYSDATA_ACCOUNT }}:" --request POST https://api.alwaysdata.com/v1/site/${{ secrets.ALWAYSDATA_BACKEND_SITE_ID }}/restart/
                      curl --basic --user "${{ secrets.ALWAYSDATA_TOKEN }} account=${{ secrets.ALWAYSDATA_ACCOUNT }}:" --request POST https://api.alwaysdata.com/v1/site/${{ secrets.ALWAYSDATA_FRONTEND_SITE_ID }}/restart/
